name: 'Deploy to environments'
description: 'Deploys to all environments matching a regular expression, with optional excluded environments'
author: "Thor Lyster Lind"
inputs:
  gh-token:
    description: 'Github Token'
    required: true
  ref:
    description: 'Git ref to be deployed to environments, defaults to `latest release`'
    required: false
    default: 'latest_release'
  environments:
    description: 'Regular expression environment names must match'
    required: true
  excluded:
    description: 'Regular expressions which environment who`s name matches will be excluded (list of regexes seperated by ;)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Deploy environments
      run: create_deployments.sh "${{ github.repository }}" "${{ inputs.ref }}" "${{ inputs.environments }}" "${{ inputs.excluded }}"
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}


branding:
  icon: upload-cloud
  color: yellow
